---
abstract: "add the author's pledge to the distribution"
author:
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
build_requires:
  Carp: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::DZil: 0
  Test::More: 0.94
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Covenant
provides:
  Dist::Zilla::Plugin::Covenant:
    file: lib/Dist/Zilla/Plugin/Covenant.pm
    version: v0.1.0
requires:
  Dist::Zilla::File::InMemory: 0
  Dist::Zilla::Role::InstallTool: 0
  Dist::Zilla::Role::Plugin: 0
  Dist::Zilla::Role::TextTemplate: 0
  Moose: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-Covenant
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-Covenant/
  repository: https://github.com/yanick/Dist-Zilla-Plugin-Covenant.git
version: 0.1.0
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
